# Generated by Django 5.2.1 on 2025-05-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'contact_table',
            },
        ),
        migrations.CreateModel(
            name='contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=225)),
                ('lastname', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'contact_page',
            },
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('rating', models.CharField(choices=[('outstanding', 'Outstanding'), ('good', 'Good'), ('ok', 'Ok'), ('bad', 'Bad')], max_length=30)),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'feedback_table',
            },
        ),
        migrations.CreateModel(
            name='horoscopedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('day', models.IntegerField()),
                ('horoscope', models.CharField()),
            ],
            options={
                'db_table': 'Horoscope_table',
            },
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=20)),
                ('email', models.EmailField(max_length=254, primary_key='true', serialize=False)),
                ('mobile', models.BigIntegerField(unique='true')),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'registration_table',
            },
        ),
        migrations.CreateModel(
            name='zodiacdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_month', models.CharField(max_length=255)),
                ('birth_day', models.IntegerField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('astro_sign', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Zodiac_sign',
            },
        ),
    ]
